FROM openjdk:17-jdk-slim
WORKDIR /app
COPY target/JVMParamsCompare-0.0.1-SNAPSHOT.jar /app
ENTRYPOINT ["java", "-jar", "-XX:+UseG1GC", "-XX:InitiatingHeapOccupancyPercent=45", "-Xms8g", "-Xmx8g", "-XX:MaxGCPauseMillis=1000", "-XX:G1NewSizePercent=20", "-XX:G1MaxNewSizePercent=60", "-XX:ConcGCThreads=4", "-XX:ParallelGCThreads=8", "-XX:LargePageHeapSizeThreshold=128m", "-Xss1m", "/app/JVMParamsCompare-0.0.1-SNAPSHOT.jar"]
