FROM openjdk:17-jdk-slim
WORKDIR /app
COPY target/JVMParamsCompare-0.0.1-SNAPSHOT.jar /app
ENTRYPOINT ["java", "-jar", "-XX:+UseConcMarkSweepGC", "-Xms4g", "-Xmx4g", "-XX:CMSInitiatingOccupancyFraction=60", "-XX:+UseCMSInitiatingOccupancyOnly", "-XX:MaxGCPauseMillis=250", "-XX:NewSize=1g", "-XX:MaxNewSize=1g", "-XX:SurvivorRatio=8", "-Xss512k", "-XX:ParallelGCThreads=8", "-XX:ConcGCThreads=2", "/app/JVMParamsCompare-0.0.1-SNAPSHOT.jar"]
