FROM openjdk:17-jdk-slim
WORKDIR /app
COPY target/JVMParamsCompare-0.0.1-SNAPSHOT.jar /app
ENTRYPOINT ["java", "-jar", "-XX:+UseG1GC", "-Xms16g", "-Xmx16g", "-XX:MaxGCPauseMillis=200", "-XX:InitiatingHeapOccupancyPercent=70", "-XX:G1NewSizePercent=15", "-XX:G1MaxNewSizePercent=45", "-Xss256k", "-XX:+HeapDumpOnOutOfMemoryError", "-XX:+CrashOnOutOfMemoryError", "/app/JVMParamsCompare-0.0.1-SNAPSHOT.jar"]
